version: '3'
services:
  api:
    build: ./api
    
    # Added stdin_open, tty for docker attach to use byebug debugging 
    stdin_open: true
    tty: true

    ports:
      - '3000:3000'
    command: /bin/sh -c "rm -f /myapp/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'" 
    volumes:
      - ./api:/myapp
    depends_on:
      - db
      - test-db

  db:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports: 
      - '5432:5432'
  
  test-db:
    image: postgres  
    volumes:  
      - dbtest:/var/lib/postgresql/data
    ports:  
      - '5433:5432'  
  
  front:
    build: ./front
    command: yarn start
    ports:
      - '8000:3000'
    volumes:
      - ./front:/myapp
    depends_on:
      - api

volumes:
  dbdata:
  dbtest:

